# Generated by Django 5.0.1 on 2024-03-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_chapter_number_of_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='class',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='slug',
        ),
    ]
