# Generated by Django 5.0.1 on 2024-03-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_chapter_slug_remove_class_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
