# Generated by Django 5.0.1 on 2024-03-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
