# Generated by Django 5.0.1 on 2024-03-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
